### ISSUE TITLE
Styling the homepage

### ISSUE THREAD

**Issue by Helaly96** [DyaPlus/SE2018G27#11]
it's urgently needed to design the homepage

**Comment by AAlWali** [comment]
it's the footer put the desired links as you want


[Footer.zip](https://github.com/DyaPlus/SE2018G27/files/2849185/Footer.zip)

**Comment by abdullahshaker10** [comment]
First design of home page
[Webpage.zip](https://github.com/DyaPlus/SE2018G27/files/2851266/Webpage.zip)
